[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

# Windows default main-thread stack is 1MB, not enough for RustPython debug mode
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/STACK:8388608"]

[env]
# RustPython needs more than the default 2MB thread stack in debug mode
RUST_MIN_STACK = "8388608"
FREEZE_SEEDS = "dataclasses,encodings,enum,typing,spython"
FREEZE_EXTRA_DIR = { value = "lib", relative = true }
TYPESHED_ALLOWLIST = { value = "typeshed_allowlist.txt", relative = true }
